### ISSUE TITLE
camelCase completion memorize parenthesis

### ISSUE THREAD

**Issue by ghost** [joefitzgerald/autocomplete-go#55]
Please adjust the autocomplete to fit in line with other editors (Vscode and IntelliJ). The camelCase completion is available in here but only for a very few amount of types for some reason. strings.SA does return nothing. In VScode and IntelliJ it returns SplitAfter. So(e, SNBN) completes to So(e, ShouldNotBeNil) in those tools in Atom it's just an error. On the other hand it does work if I use FI for FileInfo which is really strange. Contrary in both of the tools it works for any part as long as the camel case is written correctly (SpAfN actually does get autocompleted to SplitAfterN in VSCode, which obviously does not work in Atom which is really frustrating). Appearently in Atom it doesn't even care about camelCase. If I write strings.CR (uppercase) i get "c context.Context, w http.ResponseWriter, r *http.Request" (cr lowercase) which is pretty let's say strange. In VSCode you only get the actual members of that package you are referencing by the dot notation. 

Also why can I write cr to get cwr but I can't write CA to get ContainsAny??? I mean that really does not sound logical to me.

Also in VScode and IntelliJ if you add a parenthesis due to tabbing an autosuggested function  that parenthesis will be remembers. Means if you write that closing parenthesis the second time it will just be ignored saving a lot of time and headaches. Applies to all of those chars: " ' {([])} , .

**Comment by zmb3** [comment]
The fuzzy matching behavior you're requesting is duplicated by issue #19.

The `cwr` completion you see is a _snippet_ provided by the [language-go](https://github.com/atom/language-go/blob/master/snippets/language-go.cson#L92) package.  If this behavior isn't working well for you then you may consider providing feedback on that package.

> Also why can I write cr to get cwr but I can't write CA to get ContainsAny???

Because `cwr` is a snippet and `ContainsAny` would be a gocode suggestion.  As mentioned in #19, we'd welcome a contribution that adds this functionality.

> Also in VScode and IntelliJ if you add a parenthesis due to tabbing an autosuggested function that parenthesis will be remembers.

I can't speak for IntelliJ but in VS Code I'm seeing that the opening `(` is not inserted for you when accepting a suggestion.  This is the same behavior as autocomplete-go.

**Comment by ghost** [comment]
Thanks for the link. In fact disabling the surpress built-in option does enable a fuzzy search (although it is not comparable to VSCode or IntelliJ but it definitely is usable).

I think you misunderstood the last part or I wrongly expressed it. Anyway after doing a fresh install of Atom (deleting ~/.atom obviously) it works way the way I expected. So maybe I did break something during the last installation. At least it does work now.
